config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("kanban/", include("kanban.urls")),
    path("kanban/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

kanban/urls.py
from django.urls import path

from . import views

app_name = "kanban"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
]

kanban/models.py
from django.db import models

# Create your models here.

kanban/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from django.http import HttpResponse


def index(request):
    return render(request, "kanban/index.html")

@login_required
def home(request):
    return render(request, "kanban/home.html")


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user_instance = form.save()
            login(request, user_instance)
            return redirect("kanban:home")
    else:
        form = UserCreationForm()
    context = {
        "form": form
    }
    return render(request, 'kanban/signup.html', context)

kanban/templates/kanban/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>kanban</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'kanban:index' %}">kanban</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <span class="navbar-text">
              こんにちは {{ request.user.username }} さん
            </span>
            <li class="nav-item">
              <a href="{% url 'logout' %}" class="nav-link">ログアウト</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">ログイン</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kanban:signup' %}">サインアップ</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

kanban/templates/kanban/home.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ完了</h1>
  <p>サインアップが完了しました。</p>
</div>
{% endblock %}

kanban/templates/kanban/index.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">kanban</h1>
  <p class="lead">kanbanでタスク管理をしてみましょう。</p>
  <hr class="my-4">
  <p>このアプリケーションはDjangoで作られています。</p>
  <a href="{% url 'login' %}" class="btn btn-primary btn-lg" role="button">ログイン</a>
  <a href="{% url 'kanban:signup' %}" class="btn btn-primary btn-lg" role="button">サインアップ</a>
</div>
{% endblock %}

kanban/templates/kanban/signup.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">登録</button>
  </form>
</div>
{% endblock %}